name: Translations

on:
  push:
    branches: [ master ]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: crowdin action
      uses: crowdin/github-action@1.0.3
      with:
        upload_translations: true
        download_translations: true
      env:
        GITHUB_TOKEN: ${{ secrets.git_token }}
        project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
        api_token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
